name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate Snake with Calendar Labels
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-snake.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: no
          plugin_habits_trim: no
          config_timezone: Asia/Jakarta
          config_output: svg
          output_action: commit
          committer_branch: main
          
      - name: Generate Isocalendar (3D with labels)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Jakarta
          config_output: svg
          output_action: commit
          committer_branch: main
